# Generated by Django 3.2.6 on 2021-08-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('group', models.CharField(default=None, max_length=10, null=True)),
                ('course', models.IntegerField(default=None, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='VKMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=4096)),
                ('date', models.DateField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vk_bot.vkuser')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
