# Generated by Django 3.2.6 on 2021-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='course',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='group',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
