# Generated by Django 3.2.6 on 2021-08-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0004_auto_20210814_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='status',
            field=models.CharField(blank=True, choices=[('reg1', 'Course registration'), ('reg2', 'Group registration'), ('any', 'Available for any function'), ('link', 'Links to classes'), ('sch', 'Schedule')], default='any', max_length=4),
        ),
    ]
