# Generated by Django 3.2.6 on 2021-08-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0006_textanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanswer',
            name='CHOOSE_COURSE',
            field=models.TextField(default='Для продолжения пройдите краткую регистрацию\nВыберите курс'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='CHOOSE_COURSE_TO_CONTINUE',
            field=models.TextField(default='Для продолжения выберите курс'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='CHOOSE_GROUP',
            field=models.TextField(default='Выберите группу'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='CHOOSE_GROUP_TO_CONTINUE',
            field=models.TextField(default='Для продолжения выберите группу'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='REG_END',
            field=models.TextField(default='Вы успешно прошли регистрацию. Для изменения данных введите "Изменить данные"'),
        ),
    ]
