# Generated by Django 3.2.6 on 2021-08-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0007_auto_20210814_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextAnswer',
        ),
        migrations.RenameField(
            model_name='vkuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
