# Generated by Django 3.2.6 on 2021-08-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0010_alter_vkuser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='group',
            field=models.CharField(blank=True, choices=[('Б03-111', 'Б03-111'), ('Б03-112', 'Б03-112'), ('Б03-113', 'Б03-113'), ('Б03-114', 'Б03-114'), ('Б03-115', 'Б03-115'), ('Б03-011', 'Б03-011'), ('Б03-012', 'Б03-012'), ('Б03-013', 'Б03-013'), ('Б03-014', 'Б03-014'), ('Б03-015', 'Б03-015'), ('Б03-911', 'Б03-911'), ('Б03-912', 'Б03-912'), ('Б03-913', 'Б03-913'), ('Б03-914', 'Б03-914'), ('Б03-915', 'Б03-915'), ('Б03-861', 'Б03-861'), ('Б03-862', 'Б03-862'), ('Б03-863', 'Б03-863'), ('Б03-864', 'Б03-864'), ('Б03-865', 'Б03-865')], max_length=8, null=True),
        ),
    ]
